name: continous-deployment 
run-name: Deploy do App
on: 
    pull_request:
        branches:
            - main
        workflow_dispatch: 
jobs: 
    deploy:
        name: deploy
        runs-on: ubuntu-latest 

        steps:
            - uses: action/checkout@v4
            with: 
                fetch-depth: 0
                
