name: continous-deployment 
run-name: Deploy do App
on: 
  # push: 
    # branches: 
        # - dev
  
    pull_request:
        branches:
            - main
    workflow_dispatch: 
jobs: 
    deploy:
        name: deploy
        runs-on: ubuntu-latest 

        steps:
            - uses: actions/checkout@v4
              with: 
                fetch-depth: 0

            - name: Docker login
              uses: docker/login-action@v3.4.0
              with:
                username: ${{ secrets.DOCKER_USER }}
                password: ${{ secrets.DOCKER_PASSWORD }}


            - name: Build and push Dokcer image
              uses: docker/build-push-action@v6.15.0
              with: 
                context: .
                file: ./Dockerfile
                push: true
                tags: arthsz-ti/devops-trabalho:latest
                
            - name: Azure WebApp
              uses: Azure/webapps-deploy@v3.0.1
              with: 
                    app-name: arthsz-ti-devops-trabalho
                    publish-profile: ${{ secrets.PUBLISH_PROFILE }}
                    image: arthsz-ti/devops-trabalho:latest
